UPDATE `deviceList` SET `deviceType`= '' WHERE 


-- Android
`deviceName` = 'Alfred Pennworth' OR
`deviceName` = 'Aqualad' OR
`deviceName` = 'AquaMan' OR
`deviceName` = 'Artemis' OR
`deviceName` = 'Bane' OR
`deviceName` = 'Batman' OR
`deviceName` = 'Beast Boy' OR
`deviceName` = 'Black Canary' OR
`deviceName` = 'Blue Beetle' OR
`deviceName` = 'Booster Gold' OR
`deviceName` = 'Brainiac' OR
`deviceName` = 'Bumblebee' OR
`deviceName` = 'Cyborg' OR
`deviceName` = 'Deathstroke' OR
`deviceName` = 'Doomsday' OR
`deviceName` = 'Dr Fate' OR
`deviceName` = 'Etrigan' OR
`deviceName` = 'Flash' OR
`deviceName` = 'Green Arrow' OR
`deviceName` = 'Green Lantern' OR
`deviceName` = 'Grundy' OR
`deviceName` = 'Guardian' OR
`deviceName` = 'Hawkgirl' OR
`deviceName` = 'Hawkman' OR
`deviceName` = 'Inque' OR
`deviceName` = 'Krypto' OR
`deviceName` = 'Lex Luthor' OR
`deviceName` = 'Lobo' OR
`deviceName` = 'Martian Manhunter' OR
`deviceName` = 'Mirror Master' OR
`deviceName` = 'Mr. Freeze' OR
`deviceName` = 'Oracle' OR
`deviceName` = 'Penguin' OR
`deviceName` = 'Plastic Man' OR
`deviceName` = 'Raven' OR
`deviceName` = 'RedHood' OR
`deviceName` = 'Scarecrow' OR
`deviceName` = 'Shazam' OR
`deviceName` = 'Starfire' OR
`deviceName` = 'Static Shock' OR
`deviceName` = 'SuperBoy' OR
`deviceName` = 'Superman' OR
`deviceName` = 'Two Face' OR
`deviceName` = 'Wonder Woman' OR
`deviceName` = 'Zatanna'


-- Kindle
`deviceName` = 'Black Adam' OR
`deviceName` = 'Harley' OR
`deviceName` = 'Joker' OR
`deviceName` = 'Mr. Mxyzptlk' OR
`deviceName` = 'Sinestro'


-- iOS
`deviceName` = 'Angel' OR
`deviceName` = 'Ant Man' OR
`deviceName` = 'Apocalypse' OR
`deviceName` = 'Binary' OR
`deviceName` = 'Bingo' OR
`deviceName` = 'Bishop' OR
`deviceName` = 'Blink' OR
`deviceName` = 'Cable' OR
`deviceName` = 'Captain America' OR
`deviceName` = 'Crossbones' OR
`deviceName` = 'Dazzler' OR
`deviceName` = 'DeadPool' OR
`deviceName` = 'Doctor Doom' OR
`deviceName` = 'Doctor Strange' OR
`deviceName` = 'Galactus' OR
`deviceName` = 'Hulk' OR
`deviceName` = 'Jubilee' OR
`deviceName` = 'Juggernaut' OR
`deviceName` = 'Lockheed' OR
`deviceName` = 'Luke Cage' OR
`deviceName` = 'Magneto' OR
`deviceName` = 'Medusa' OR
`deviceName` = 'Moon Knight' OR
`deviceName` = 'Mystique' OR
`deviceName` = 'Polaris' OR
`deviceName` = 'Quicksilver' OR
`deviceName` = 'Red Skull' OR
`deviceName` = 'Scarlet Witch' OR
`deviceName` = 'Sif' OR
`deviceName` = 'Silk' OR
`deviceName` = 'Silver Surfer' OR
`deviceName` = 'Spiderman' OR
`deviceName` = 'Squirrel Girl' OR
`deviceName` = 'Storm' OR
`deviceName` = 'Thanos' OR
`deviceName` = 'Thor' OR
`deviceName` = 'Venom' OR
`deviceName` = 'Vision' OR
`deviceName` = 'Wolverine'